name: Lint Files
# Run on All Branches except when merging
on:
  push:
    branches-ignore:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-my-portfolio:
    name: Lint My-Portfolio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use NodeJS v22.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0
      - name: Install Dependencies
        run: |
          npm install
      - name: Lint
        run: | 
          npm run lint